ALTER TABLE IF EXISTS links RENAME COLUMN url TO uri;
ALTER TABLE IF EXISTS links RENAME COLUMN name TO title;

ALTER TABLE IF EXISTS links ADD type VARCHAR;
ALTER TABLE IF EXISTS links ADD parent_id INT REFERENCES links(id) ON DELETE CASCADE;
ALTER TABLE IF EXISTS links ADD created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE IF EXISTS links ADD updated_at TIMESTAMPTZ DEFAULT NOW();
